### ISSUE TITLE
Specify dependencies otherwise latest (incorrect ones) are used.

### ISSUE THREAD

**Issue by necro-nemesis** [adamkovesdi/esp-matrixclock#3]
Builds but runs with errors. Possibly update platormio.ini with specific deps vs global ones. I've tried some older versions but don't know what combination of dependencies were used. Platformio will pull the latest when they're global unless the specific ones are added manually but they clearly aren't the ones.

**Comment by adamkovesdi** [comment]
Thanks for this. I haven't touched the source in quite a while. The clock is just working(TM) on my shelf for years now. :)

It was using ArduinoJson version 5 and the current is 6.
If I'll have time I'll migrate the project to version 6. As for now, I fixed this issue by specifying ArduinoJson version 5.13.4 (thanks to one of my forkers) see commit 40d3150
